services:
  pg-identity:
    container_name: pg-identity
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - finances-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - finances-network

  
  finances-identity:
    container_name: finances-identity
    image: finances-identity:latest
    build: 
      context: .
      dockerfile: ./FinancesIdentityServer/Dockerfile
      args:
        NEXUS_URL: http://localhost:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+80
      - ConnectionStrings__DefaultConnection=Server=pg-identity:5432;User Id=postgres;Password=1234;Database=identity
      - RabbitMq__Host=rabbitmq
    ports:
      - 5000:80
    depends_on:
      - pg-identity
      - rabbitmq
    networks:
      - finances-network

  finances-api:
    container_name: finances-api
    image: finances-api:latest
    build: 
      context: .
      dockerfile: ./Finances/Dockerfile
      args:
        NEXUS_URL: http://localhost:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+80
      - ConnectionStrings__ApiDatabase=Server=pg-identity:5432;User Id=postgres;Password=1234;Database=identity
      - ConnectionStrings__HangfireConnection=Server=pg-identity:5432;User Id=postgres;Password=1234;Database=identity
      - RabbitMq__Host=rabbitmq
      - IdentityServerUrl=http://finances-identity
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7001
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
      - 6001:80
      - 7001:7001
    depends_on:
      - pg-identity
      - rabbitmq
    networks:
      - finances-network

networks:
  finances-network:
    external: true

volumes:
  pg_data: